### ISSUE TITLE
onaudioprocess not fired, or stops being called

### ISSUE THREAD

**Issue by Debetux** [roparz/Recordmp3js#1]
Hi,

It seems that recorder.onaudioprocess have some problem on Chrome and Chromium (not tried with Firefox yet).
There's some reported issues : https://code.google.com/p/chromium/issues/detail?id=71951 and the more revelant : https://code.google.com/p/chromium/issues/detail?id=360378

But, I didn't find out how to fix that in your code.

**Comment by roparz** [comment]
Hi @Debetux ,

Thank you for the feedback (and sorry about my late answer).

I just tried to make a record and it seems to be working.
However, I made some changes that will maybe fix that bug.
Could you try it ?
